name: python-deployment
run-name: ${{ github.actor }} - ${{ github.ref_name }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.8
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  python-ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
     run:
      working-directory: ./src

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Setup Python ${{ env.PYTHON_VERSION }}
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install flake8
           pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          cd ../
          flake8 . --show-source --statistics
