global:
 ENVIRONMENT: "Staging"

kube2py:
 configs:
   APP_ENV: "testing-helm-staging"

 secrets:
   password: MyPassword!
   login: MyUser

 resources:
   requests:
      memory: "256Mi"
      cpu: "100m"
   limits:
     memory: "256Mi"
     cpu: "100m"

 hpa:
  enabled: True
  minReplicas: 3
  maxReplicas: 5
